### ISSUE TITLE
Benchmarks don't compile

### ISSUE THREAD

**Issue by fancywriter** [gnieh/tekstlib#13]
I don't know what can I do wrong, but `sbt "benchmarks/test:compile"` fails with errors for me. Starting from `not found: type MustacheParser` on SimpleBenchmark.scala:34.

If it is not intended to run with `sbt test`, please add this information to README how to run it. Or does it require additional setup to work with `sbt test`?

**Comment by satabin** [comment]
This looks like a bug. I will check.

**Comment by satabin** [comment]
Ok it is fixed, benchmarks now live in `src/bench` and are executed with `bench:test`.

**Comment by fancywriter** [comment]
Do you have any ideas how to run only one benchmark from sbt? `test-only` didn't work for me. Or how to temporary ignore benchmarks?

**Comment by satabin** [comment]
Last time I checked, `testOnly` did work for me. I updated scalameter maybe there is some change there.
