### ISSUE TITLE
Nesting when using vertical alignments misses first line.

### ISSUE THREAD

**Issue by tonicebrian** [gnieh/tekstlib#4]
Code of kind:

```
nest(2)(vcat(List(TextDoc("line"))))
```
seems to miss rendering first line nested.

Here https://github.com/tonicebrian/tekstlib/blob/hotfix/nesting_vertical_elements/src/test/scala/gnieh/pp/tests/ListCombinatorsTest.scala#L34,L39

I've started an attempt to fix it but seems like removing indentation in https://github.com/tonicebrian/tekstlib/blob/hotfix/nesting_vertical_elements/src/main/scala/gnieh/pp/SimpleDoc.scala#L68 breaks other tests so I'm not aware of the ramifications.

**Comment by satabin** [comment]
Hi,

I haven’t work on this code for some times now, so I need to dive into the code to remember how it works. I will check what is going wrong there.

Thanks for reporting

**Comment by satabin** [comment]
Hi,

I remember now, the semantics of the `nest` operator is to add the indentation after each new line, which, de facto, excludes the first line. So it is not a bug but a feature.

It allows you to write this:

```scala
nest(4)("def toto():" :|: "print('toto')")
```

and it renders as
```
def toto():
    print('toto')
```

**Comment by satabin** [comment]
for more details you can refer to the paper that inspired the implementation: http://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf

**Comment by tonicebrian** [comment]
Ahh OK. I mistook the `nest` command for the `indent` functionality that I saw in https://hackage.haskell.org/package/ansi-wl-pprint-0.6.7.3/docs/Text-PrettyPrint-ANSI-Leijen.html#v:indent. 

It seems like both commands exist in the Haskell implementation so I created a PR with the new missing `indent` command. Hopefully you find it useful for including it in next release.

**Comment by satabin** [comment]
Thanks I will review it.
